version: "3.8"
services:

  web-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - common_network

  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - common_network

networks:
  common_network:



